# Generated by Django 4.1.6 on 2023-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_desc', models.CharField(max_length=128)),
                ('set_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_desc', models.CharField(max_length=128)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_sold', models.DateTimeField()),
                ('item_sets', models.ManyToManyField(to='shop.set')),
            ],
        ),
    ]
