# Generated by Django 4.1.6 on 2023-02-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_item_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
