# Generated by Django 4.1.6 on 2023-02-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_item_item_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_sets',
            new_name='sets',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_sold',
            new_name='sold',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='set_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='set_price',
            new_name='price',
        ),
    ]
