# Generated by Django 4.1.6 on 2023-02-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_set_options_set_items_alter_item_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sold',
            new_name='sold_at',
        ),
    ]
