# Generated by Django 4.1.6 on 2023-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_sold_item_sold_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('items', models.ManyToManyField(blank=True, to='shop.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='repositories',
            field=models.ManyToManyField(blank=True, to='shop.repository'),
        ),
    ]
