# Generated by Django 4.1.6 on 2023-03-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_repository_item_repositories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'repositories'},
        ),
    ]
