# Generated by Django 4.1.6 on 2023-03-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_repository_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='images',
            field=models.ManyToManyField(to='shop.image'),
        ),
    ]
