# Generated by Django 4.1.6 on 2023-03-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_image_set_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='images',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(blank=True, to='shop.image'),
        ),
    ]
