# Generated by Django 4.1.6 on 2023-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
