# Generated by Django 4.1.6 on 2023-04-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sets',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='shop.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='sets',
            field=models.ManyToManyField(blank=True, null=True, to='shop.set'),
        ),
    ]
