# Generated by Django 4.1.6 on 2023-04-22 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_order_user_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='shop.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sets',
            field=models.ManyToManyField(blank=True, to='shop.set'),
        ),
    ]
