# Generated by Django 4.1.6 on 2023-04-22 18:57

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_order_creation_time_alter_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=shop.models.generate_order_number, unique=False),
        ),
    ]
