# Generated by Django 4.1.6 on 2023-04-22 18:58

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(default=shop.models.generate_order_number),
        ),
    ]
