# Generated by Django 4.1.6 on 2023-04-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0020_alter_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_address', models.CharField(blank=True, max_length=128, null=True)),
                ('addr_city', models.CharField(blank=True, max_length=128, null=True)),
                ('addr_country', models.CharField(blank=True, max_length=128, null=True)),
                ('addr_county', models.CharField(blank=True, max_length=128, null=True)),
                ('addr_postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('card_number', models.IntegerField(blank=True, null=True)),
                ('card_name', models.CharField(blank=True, max_length=128, null=True)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('card_cvc', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
