# Generated by Django 4.1.6 on 2023-04-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_set_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
